# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/ECE532/test_gyro/test_gyro.cache/wt [current_project]
set_property parent.project_path C:/ECE532/test_gyro/test_gyro.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {C:/ECE532/board_files} [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo c:/ECE532/test_gyro/test_gyro.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/hdl/block1_wrapper.v
add_files C:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/block1.bd
set_property used_in_implementation false [get_files -all c:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/ip/block1_axi_iic_0_1/block1_axi_iic_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/ip/block1_axi_iic_0_1/block1_axi_iic_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/ip/block1_dlmb_v10_0/block1_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/ip/block1_dlmb_v10_0/block1_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/ip/block1_ilmb_v10_0/block1_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/ip/block1_ilmb_v10_0/block1_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/ip/block1_dlmb_bram_if_cntlr_0/block1_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/ip/block1_ilmb_bram_if_cntlr_0/block1_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/ip/block1_lmb_bram_0/block1_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/ip/block1_xbar_0/block1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/ip/block1_rst_clk_wiz_1_100M_0/block1_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/ip/block1_rst_clk_wiz_1_100M_0/block1_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/ip/block1_rst_clk_wiz_1_100M_0/block1_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/ip/block1_microblaze_0_0/block1_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/ip/block1_microblaze_0_0/block1_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/ip/block1_microblaze_0_0/block1_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/ip/block1_mdm_1_0/block1_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/ip/block1_mdm_1_0/block1_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/ip/block1_microblaze_0_axi_intc_0/block1_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/ip/block1_microblaze_0_axi_intc_0/block1_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/ip/block1_microblaze_0_axi_intc_0/block1_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/ip/block1_clk_wiz_1_0/block1_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/ip/block1_clk_wiz_1_0/block1_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/ip/block1_clk_wiz_1_0/block1_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/ECE532/test_gyro/test_gyro.srcs/sources_1/bd/block1/block1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/ECE532/test_gyro/test_gyro.srcs/constrs_1/new/gyroTest.xdc
set_property used_in_implementation false [get_files C:/ECE532/test_gyro/test_gyro.srcs/constrs_1/new/gyroTest.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top block1_wrapper -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef block1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file block1_wrapper_utilization_synth.rpt -pb block1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
