# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/gyroTest.xdc

# Block Designs: bd/block1/block1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1 || ORIG_REF_NAME==block1} -quiet] -quiet

# IP: bd/block1/ip/block1_axi_iic_0_1/block1_axi_iic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_axi_iic_0_1 || ORIG_REF_NAME==block1_axi_iic_0_1} -quiet] -quiet

# IP: bd/block1/ip/block1_dlmb_v10_0/block1_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_dlmb_v10_0 || ORIG_REF_NAME==block1_dlmb_v10_0} -quiet] -quiet

# IP: bd/block1/ip/block1_ilmb_v10_0/block1_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_ilmb_v10_0 || ORIG_REF_NAME==block1_ilmb_v10_0} -quiet] -quiet

# IP: bd/block1/ip/block1_dlmb_bram_if_cntlr_0/block1_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==block1_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/block1/ip/block1_ilmb_bram_if_cntlr_0/block1_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==block1_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/block1/ip/block1_lmb_bram_0/block1_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_lmb_bram_0 || ORIG_REF_NAME==block1_lmb_bram_0} -quiet] -quiet

# IP: bd/block1/ip/block1_xbar_0/block1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_xbar_0 || ORIG_REF_NAME==block1_xbar_0} -quiet] -quiet

# IP: bd/block1/ip/block1_microblaze_0_axi_periph_0/block1_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==block1_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/block1/ip/block1_rst_clk_wiz_1_100M_0/block1_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==block1_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/block1/ip/block1_microblaze_0_xlconcat_0/block1_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_microblaze_0_xlconcat_0 || ORIG_REF_NAME==block1_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/block1/ip/block1_microblaze_0_0/block1_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_microblaze_0_0 || ORIG_REF_NAME==block1_microblaze_0_0} -quiet] -quiet

# IP: bd/block1/ip/block1_mdm_1_0/block1_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_mdm_1_0 || ORIG_REF_NAME==block1_mdm_1_0} -quiet] -quiet

# IP: bd/block1/ip/block1_microblaze_0_axi_intc_0/block1_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_microblaze_0_axi_intc_0 || ORIG_REF_NAME==block1_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/block1/ip/block1_clk_wiz_1_0/block1_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_clk_wiz_1_0 || ORIG_REF_NAME==block1_clk_wiz_1_0} -quiet] -quiet

# XDC: bd/block1/block1_ooc.xdc
