# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/tx/tx.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tx || ORIG_REF_NAME==tx} -quiet] -quiet

# IP: bd/tx/ip/tx_clk_wiz_0_0/tx_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tx_clk_wiz_0_0 || ORIG_REF_NAME==tx_clk_wiz_0_0} -quiet] -quiet

# IP: bd/tx/ip/tx_ov7670_controller_0_0/tx_ov7670_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tx_ov7670_controller_0_0 || ORIG_REF_NAME==tx_ov7670_controller_0_0} -quiet] -quiet

# IP: bd/tx/ip/tx_debounce_0_0/tx_debounce_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tx_debounce_0_0 || ORIG_REF_NAME==tx_debounce_0_0} -quiet] -quiet

# IP: bd/tx/ip/tx_ov7670_capture_0_1/tx_ov7670_capture_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tx_ov7670_capture_0_1 || ORIG_REF_NAME==tx_ov7670_capture_0_1} -quiet] -quiet

# IP: bd/tx/ip/tx_streamer_0_0/tx_streamer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tx_streamer_0_0 || ORIG_REF_NAME==tx_streamer_0_0} -quiet] -quiet

# IP: bd/tx/ip/tx_packetizer_0_0/tx_packetizer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tx_packetizer_0_0 || ORIG_REF_NAME==tx_packetizer_0_0} -quiet] -quiet

# IP: bd/tx/ip/tx_axi_ethernetlite_0_0/tx_axi_ethernetlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tx_axi_ethernetlite_0_0 || ORIG_REF_NAME==tx_axi_ethernetlite_0_0} -quiet] -quiet

# IP: bd/tx/ip/tx_mii_to_rmii_0_0/tx_mii_to_rmii_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tx_mii_to_rmii_0_0 || ORIG_REF_NAME==tx_mii_to_rmii_0_0} -quiet] -quiet

# IP: bd/tx/ip/tx_blk_mem_gen_0_0/tx_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tx_blk_mem_gen_0_0 || ORIG_REF_NAME==tx_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/tx/ip/tx_proc_sys_reset_0_0/tx_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tx_proc_sys_reset_0_0 || ORIG_REF_NAME==tx_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/tx/ip/tx_ila_0_0/tx_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tx_ila_0_0 || ORIG_REF_NAME==tx_ila_0_0} -quiet] -quiet

# XDC: bd/tx/tx_ooc.xdc
