# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/ECE532/audio_project/audio_project.cache/wt [current_project]
set_property parent.project_path C:/ECE532/audio_project/audio_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/ece532
  c:/ECE532/ip_repo/audio_axi_1.0
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/ECE532/audio_project/audio_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/ECE532/audio_project/ip_repo/audio_axi_1.0/hdl/audio_axi_v1_0_S00_AXI.v
  C:/ECE532/audio_project/audio_project.srcs/sources_1/new/audio_toplevel.v
  C:/ECE532/audio_project/audio_project.srcs/sources_1/imports/new/shift_reg.v
  C:/ECE532/audio_project/ip_repo/audio_axi_1.0/hdl/audio_axi_v1_0.v
}
read_verilog -library xil_defaultlib {
  C:/ECE532/audio_project/audio_project.srcs/sources_1/imports/new/PDM_interface.v
  C:/ECE532/audio_project/audio_project.srcs/sources_1/imports/new/clock_divider.v
  C:/ECE532/audio_project/audio_project.srcs/sources_1/imports/new/counter.v
  C:/ECE532/audio_project/audio_project.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
  C:/ECE532/audio_project/audio_project.srcs/sources_1/imports/new/enable_controller.v
  C:/ECE532/audio_project/audio_project.srcs/sources_1/new/fft_interface.v
  C:/ECE532/audio_project/audio_project.srcs/sources_1/new/twos_complement_to_magnitude.v
}
add_files C:/ECE532/audio_project/audio_project.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/ECE532/audio_project/audio_project.srcs/sources_1/bd/design_1/ip/design_1_xfft_0_0/design_1_xfft_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/ECE532/audio_project/audio_project.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top audio_axi_v1_0 -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef audio_axi_v1_0.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file audio_axi_v1_0_utilization_synth.rpt -pb audio_axi_v1_0_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
