# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/rx/rx.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rx || ORIG_REF_NAME==rx} -quiet] -quiet

# IP: bd/rx/ip/rx_depacketizer_0_0/rx_depacketizer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rx_depacketizer_0_0 || ORIG_REF_NAME==rx_depacketizer_0_0} -quiet] -quiet

# IP: bd/rx/ip/rx_clk_wiz_0_0/rx_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rx_clk_wiz_0_0 || ORIG_REF_NAME==rx_clk_wiz_0_0} -quiet] -quiet

# IP: bd/rx/ip/rx_proc_sys_reset_0_0/rx_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rx_proc_sys_reset_0_0 || ORIG_REF_NAME==rx_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/rx/ip/rx_axi_ethernetlite_0_0/rx_axi_ethernetlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rx_axi_ethernetlite_0_0 || ORIG_REF_NAME==rx_axi_ethernetlite_0_0} -quiet] -quiet

# IP: bd/rx/ip/rx_mii_to_rmii_0_0/rx_mii_to_rmii_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rx_mii_to_rmii_0_0 || ORIG_REF_NAME==rx_mii_to_rmii_0_0} -quiet] -quiet

# IP: bd/rx/ip/rx_ila_0_0/rx_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rx_ila_0_0 || ORIG_REF_NAME==rx_ila_0_0} -quiet] -quiet

# IP: bd/rx/ip/rx_blk_mem_gen_0_0/rx_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rx_blk_mem_gen_0_0 || ORIG_REF_NAME==rx_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/rx/ip/rx_ov7670_vga_0_0/rx_ov7670_vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rx_ov7670_vga_0_0 || ORIG_REF_NAME==rx_ov7670_vga_0_0} -quiet] -quiet

# XDC: bd/rx/rx_ooc.xdc
